name: Android Pull Request Check
on: [push]

jobs:
  unitTest:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: stub_for_pr_builds
      CRASHLYTICS_KEY: http://dummy.url
      MCLAREN_FEED_URL: http://dummy.url
      MCLAREN_RACE_INFO_URL: http://dummy.url
      MCLAREN_RACE_LIFE_DATA_URL: http://dummy.url
      STORYSTREAM_FEED_URL: http://dummy.url
      STORYSTREAM_TOKEN: dummy

    steps:
    - uses: actions/checkout@v1

    # - name: set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8

    - name: Unit Test
      run: ./gradlew jacocoTestDebugUnitTestReport --continue
      continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step
