name: Android Pull Request Check
on: [push]

env:
  FIRST_NAME: stub_for_pr_builds
  CRASHLYTICS_KEY: http://dummy.url
  MCLAREN_FEED_URL: http://dummy.url
  MCLAREN_RACE_INFO_URL: http://dummy.url
  MCLAREN_RACE_LIFE_DATA_URL: http://dummy.url
  STORYSTREAM_FEED_URL: http://dummy.url
  STORYSTREAM_TOKEN: dummy

jobs:
  unitTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unit Test
      run: ./gradlew jacocoTestDebugUnitTestReport --continue
      continue-on-error: true # IMPORTANT: allow pipeline to continue to Test Report step

    - name: Unit Test Report
      uses: asadmansr/android-test-report-action@v1.2.0

  uiTest:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: UI Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
